### ISSUE TITLE
isMandatory checkbox is disabled but not checked

### ISSUE THREAD

**Issue by guanacone** [porscheofficial/cookie-consent-banner#13]
```
    @porscheofficial/cookie-consent-banner-react@<3.1.2>
```

**Browser(s) version(s)**:
Version 111.0.5563.64 (Official Build) (64-bit)

**Description of the issue/feature**:
`isMandatory` checkbox is disabled but not checked

![Screenshot from 2023-03-19 11-51-38](https://user-images.githubusercontent.com/11678477/226196879-7bfc2ab9-8377-44b9-9f86-291f95fd6569.png)

**Comment by switchnollie** [comment]
Hey @guanacone sorry for the late reply 👋🏻. 
We investigated your issue and couldn't reproduce it with any version above 3, neither with the web component integration nor with the react integration. Some further questions to investigate on our side would be:

1. Can you provide the exact version of `@porscheofficial/cookie-consent-banner-react` you installed?
2. Have you tried upgrading the package to the latest version?
3. Does the issue come up when the banner is first rendered and no settings were submitted yet or when you trigger the cookie banner programmatically again via `triggerCookieConsentBanner()`?
4. Do you apply any special styling to the element?

If you could provide a code sandbox or similar, this would be even better.
Thank you for your request and the patience. 🙌🏻
