### ISSUE TITLE
Absence of the consent-state cookie is not handled correctly

### ISSUE THREAD

**Issue by dsiscout** [porscheofficial/cookie-consent-banner#14]
**Node/npm version(s)**: v19.7.0

**Package(s) version(s)**:

```
    @porscheofficial/cookie-consent-banner-react@3.1.2
```

**Browser(s) version(s)**: Chrome Version 111.0.5563.110

**Description of the issue/feature**:
The consent banner is only shown if no cookies are set. But it should be shown as long as long as the consent state cookie is not set or empty. This was also brought up here: https://github.com/porscheofficial/cookie-consent-banner/issues/12#issuecomment-1470694430

**Some example to reproduce the issue**:
 - clear cookies
 - load page -> cookie consent is shown
 - without accepting anything, navigate to another page or reload
 - the cookie consent is not shown anymore

**Use cases**:
 - the cookie consent should be shown as long as the user has not actively accepted anything.

**Comment by dsiscout** [comment]
Also, it seems like the order of where consent state cookie is return in the document.cookie string also plays a role. If the cookie is set at the beginning of the string, it doesn't work. If it is at the end of the string, it seems to work. 

Here some examples to try using following code https://github.com/porscheofficial/cookie-consent-banner/blob/main/packages/cookie-consent-banner/src/components/cookie-consent-banner/cookie-consent-banner.tsx#L131-L134

- When the cookie is set at the beginning, all other cookies are returned on for cookieValueString. Line 134 then returns false which is why the consent banner is not shown anymore.
const documentCookie = 'cookies_accepted_categories=; other_cookie=test';
\`; ${documentCookie}\`.split('; cookies_accepted_categories=').pop() ?? "".split(";").shift()

- When the cookie set at the end, an empty string is returned if nothing was yet selected. On line 134 it evaluates as true and the cookie consent banner is shown.
const documentCookie = 'other_cookie=test; cookies_accepted_categories=';
\`; ${documentCookie}\`.split('; cookies_accepted_categories=').pop() ?? "".split(";").shift()

**Comment by pboeder** [comment]
Hi @dsiscout! Thanks for clarifying the issue even more. Would highly appreciate a Pull Request. Otherwise I will look into it in the next days.

**Comment by dsiscout** [comment]
Hello @pboeder, I was able to create a fix, but unfortunately I am unable to create a PR (missing permission). If you change the following line, I was able to get all cases working:

packages/cookie-consent-banner/src/components/cookie-consent-banner/cookie-consent-banner.tsx
Line 130 change from 

if (document.cookie) {

to 

if (document.cookie && document.cookie.includes(`${this.cookieName}=\`)) {

Would appreciate if you could have a look soon.

Thx

**Comment by pboeder** [comment]
Hi @dsiscout! Thanks for the suggestion. Will soon implement the fix :)

What do you mean by missing permission to create a PR?
It should be possible. Where did you see that error?
