### ISSUE TITLE
Dark patterns are present in example image

### ISSUE THREAD

**Issue by TechnologyClassroom** [porscheofficial/cookie-consent-banner#20]
[Dark patterns](https://cookieinformation.com/resources/blog/what-are-dark-patterns-in-cookie-banners/) are present in the example image.

* 2) Pre-ticked checkboxes
* 4) Deceptive button contrast colors

I did not check to see how the banner is actively being used in the wild and that might differ.

**Comment by pboeder** [comment]
Hi @TechnologyClassroom,

thanks for the hints!

As you write, this is only an _example_ image.
The pre-ticked checkbox is set for the "technically necessary cookies". There's no decision for such cookies possible and the checkbox is just there for information purposes. However, I take your hints with me and try to provide a better example image.

Patrick

**Comment by pboeder** [comment]
Fixed with https://github.com/porscheofficial/cookie-consent-banner/commit/c635c01785c2aae616b4a2ef737576f49c9e089b.

**Comment by TechnologyClassroom** [comment]
Great job!
