### ISSUE TITLE
LCP slows down by 2.2 seconds when cookie banner is shown.

### ISSUE THREAD

**Issue by capsloq** [porscheofficial/cookie-consent-banner#7]
**Node/npm version(s)**:

**Package(s) version(s)**:

```    
    @porscheofficial/cookie-consent-banner-react@2.1.3
```

**Browser(s) version(s)**:
Chrome/Any

**Description of the issue/feature**:
Largest Contentful Paint (LCP) slows down by ~2.2 seconds when the cookie banner is shown.
Once the cookies are accepted and the banner does not pop up anymore the speed is improved by ~2.2 seconds.

**Some example to reproduce the issue**:
Using Google Lighthouse in Dev tools or https://pagespeed.web.dev/report.
**Use cases**:

**Comment by ppuritscher** [comment]
Hi @capsloq!

I tried to reproduce your issue and created a simple react app using CRA hosted with Vercel.
Ran the reports with the hosted version of Google Lighthouse (pagespeed.web.dev/report).
Unfortunately, I can see no difference.

### With Cookie Consent Banner – LCP 1.3s

<img width="972" alt="Bildschirmfoto 2022-06-23 um 13 34 07" src="https://user-images.githubusercontent.com/78862895/175289470-d24f4c4a-4676-46b9-b324-092f81328a19.png">

### Without Cookie Consent Banner Library (not just hidden) – LCP 1.3s

<img width="969" alt="Bildschirmfoto 2022-06-23 um 13 35 56" src="https://user-images.githubusercontent.com/78862895/175289745-72bb70ff-aada-4544-9dd9-56e0008ac9e7.png">


Mind to share some more information or create a codesandbox to properly reproduce the issue?

**Comment by ppuritscher** [comment]
That's interesting and sounds like a feature that should be included. Will add it to the list, thanks @capsloq!
