### ISSUE TITLE
Typescript error triggerCookieConsentBanner

### ISSUE THREAD

**Issue by zeitvertrieb** [porscheofficial/cookie-consent-banner#8]
**Node/npm version(s)**: 8.3.1

**Package(s) version(s)**: 

```
    @porscheofficial/cookie-consent-banner-react@<2.1.3>
```

**Browser(s) version(s)**: lastest Chrome

**Description of the issue/feature**: Getting an TS error: Module '"@porscheofficial/cookie-consent-banner-react"' has no exported member 'triggerCookieConsentBanner'.

**Some example to reproduce the issue**: based on demo code

**Use cases**:

**Comment by ppuritscher** [comment]
Hi @zeitvertrieb !

Sorry for the inconvenience. The documentation already includes features of the upcoming release.
Takes a bit longer than anticipated. Will notify you, once this function is available.

**Comment by learsson** [comment]
Thank you for the update, @ppuritscher!
Ok, seems straight forward. I must be honest, I did just find this project and it seems like the best CC library out there and I have yet to study the implementation.
I will start with a custom method and look for your update later

**Comment by ppuritscher** [comment]
Glad to hear that. Always open for feedback :)

**Comment by ppuritscher** [comment]
Hi @zeitvertrieb  and @learsson!

I just released `v3.0.0`. `triggerCookieConsentBanner` is now available.
See: https://github.com/porscheofficial/cookie-consent-banner/tree/main/packages/cookie-consent-banner-react#-real-world-example-with-tag-manager-and-custom-error-tracking

Please reopen this issue or create a new one if the issue still persists.
